### ISSUE TITLE
Sugestão para build do Livro

### ISSUE THREAD

**Issue by woliveiras** [ericdouglas/be-MEAN-resources#14]
Eae caras! Achei isso aqui na net: https://github.com/GitbookIO/gitbook
Seria da hora se, depois de finalizado, vocês fizessem um Build com isso. ;D

**Comment by DevCarlosAugusto** [comment]
Cara, eu vi isso do GItbook, acho bem legal!

**Comment by ericdouglas** [comment]
O @suissa estava querendo usar o gitbook mesmo, mas falei para ele que acho melhor o [Leanpub](https://leanpub.com/), pois este permite criar quantos livros quiser gratuitamente.

De qualquer forma, o livro vai ser _buildado_ com algo do tipo mesmo @woliveiras !

Obrigado pela dica! :smile:

**Comment by woliveiras** [comment]
Show de bola! :D
